"""Recreate migration

Revision ID: 3f5baa06dc87
Revises: 44c45a4753b3
Create Date: 2023-12-11 15:05:09.875287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5baa06dc87'
down_revision = '44c45a4753b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contact')
    with op.batch_alter_table('service_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('svg_content', sa.Text(), nullable=False))
        batch_op.drop_column('svg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('svg', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('svg_content')
        batch_op.drop_column('svg_filename')

    op.create_table('_alembic_tmp_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('freelance_available', sa.VARCHAR(length=10), nullable=False),
    sa.Column('email1', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
